#!/usr/bin/env python3

#from utils import *
#from sequence import *
#from short_report import *

from report_writer import *

import argparse
import json
import os

def main(args):
    with open(args.sierrapy_json) as f:
        data = json.load(f)
        sierrapy_json = data[0]
    create_output_directory(args.output_dir)
    output_path = create_output_prefix(args.output_dir, args.output_prefix)
    write_report_tables(output_path, args.sample_id, sierrapy_json)
    write_sequences_to_file(output_path, args.sample_id, sierrapy_json)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = 'Turns SierraPy JSON into useful output')
    required_args = parser.add_argument_group('required arguments')
    required_args.add_argument('-j', '--json', action='store', required=True, dest='sierrapy_json', help='JSON file from SierraPy program')
    required_args.add_argument('-i', '--id', action='store', required=True, dest='sample_id', help='Sample ID')
    required_args.add_argument('-p', '--prefix', action='store', required=True, dest='output_prefix', help='Output file prefix')
    
    parser.add_argument('-o', '--output_directory', default=os.getcwd(), action='store', dest='output_dir', help='Output directory [Default: $(pwd)]')
    args = parser.parse_args()
    main(args)


